### Simple NeuralNetWork

In [10]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [6]:
device = ("cuda" if torch.cuda.is_available() else "cpu")

In [7]:
print(f"Using {device} device")

Using cuda device


In [22]:
#building basic and simple neural network
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu = nn.Sequential(
            nn.Linear(28*28,512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10)
        )
        
    def forward(self,x):
        x = self.flatten(x)
        logits = self.linear_relu(x)
        return logits
    
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [20]:
X = torch.randn(1,28,28,device = device)

In [14]:
X

tensor([[[ 6.1199e-01, -1.1942e+00, -1.8030e-01, -4.0019e-01, -1.9106e-01,
           8.0851e-01, -1.0430e+00,  1.5764e-03, -1.6570e-01,  7.0914e-01,
          -8.9350e-01,  9.4710e-01,  2.5992e+00, -2.1815e-02, -1.1367e-01,
           1.3267e+00,  8.2591e-01,  9.2536e-01, -1.5196e-01, -3.1309e-01,
           1.8107e+00, -1.1350e+00,  3.4214e-01,  2.5071e-01,  1.8806e+00,
          -5.6765e-01,  2.9658e-01,  1.1336e+00],
         [-1.0434e-01, -2.0928e-01,  4.2977e-01, -3.9349e-01,  8.9993e-02,
           3.6427e-01,  1.4881e+00,  1.5545e+00,  8.2478e-02, -5.2435e-02,
           8.6251e-01,  1.2952e-01,  3.5314e-01, -5.3875e-01, -3.4002e-01,
           2.3986e-01, -2.4635e-01, -6.7913e-01,  9.0027e-01,  3.0231e-01,
          -1.9723e+00, -3.5731e-01,  1.9605e+00,  8.9374e-01,  7.2737e-01,
           1.4710e+00, -7.4228e-01, -1.7998e-01],
         [ 1.0619e+00,  8.8477e-01, -4.6720e-01, -7.6493e-01, -4.2835e-01,
           1.6213e-01, -5.0706e-01,  7.2560e-02,  1.7978e+00,  3.6197e-01,


In [23]:
logits = model(X)

In [30]:
softmax = nn.Softmax(dim = 1)

In [33]:
pred_probab = softmax(logits)
y_pred = pred_probab.argmax(1)

In [34]:
print(pred_probab)
print(y_pred)

tensor([[0.1207, 0.0940, 0.0908, 0.1027, 0.1023, 0.1139, 0.1044, 0.0891, 0.0889,
         0.0931]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
tensor([0], device='cuda:0')


In [27]:
X2 = torch.randn(10,28,28,device = device)

In [28]:
logits2 = model(X2)

In [37]:
pred_probab2 = softmax(logits2)
y_pred2 = pred_probab2.argmax(1)

In [38]:
print(pred_probab2)
print(y_pred2)

tensor([[0.1115, 0.0959, 0.0936, 0.0948, 0.1109, 0.1058, 0.1031, 0.0929, 0.0994,
         0.0920],
        [0.1095, 0.0920, 0.0904, 0.1029, 0.0964, 0.1123, 0.1015, 0.0961, 0.1035,
         0.0954],
        [0.1169, 0.1081, 0.0907, 0.0956, 0.0919, 0.1034, 0.0890, 0.1012, 0.1062,
         0.0969],
        [0.1083, 0.0911, 0.0947, 0.1008, 0.1018, 0.0986, 0.0958, 0.0918, 0.1137,
         0.1034],
        [0.1060, 0.0973, 0.0879, 0.0976, 0.1017, 0.0988, 0.1135, 0.0909, 0.0976,
         0.1087],
        [0.1036, 0.1002, 0.0890, 0.0990, 0.0999, 0.1103, 0.1116, 0.0893, 0.1101,
         0.0869],
        [0.0998, 0.1011, 0.0869, 0.1040, 0.0990, 0.1177, 0.1016, 0.0986, 0.1056,
         0.0857],
        [0.1081, 0.0925, 0.0921, 0.1117, 0.1122, 0.0940, 0.1112, 0.0848, 0.0930,
         0.1004],
        [0.1033, 0.1035, 0.0869, 0.0986, 0.0996, 0.1070, 0.0930, 0.0993, 0.1001,
         0.1087],
        [0.1056, 0.0905, 0.0831, 0.1110, 0.1058, 0.1016, 0.1047, 0.0874, 0.1118,
         0.0985]], device='c

In [52]:
#Model Parameters
for name, parameter in model.named_parameters():
    # print(f"layer name:{name} | size:{parameter.size()} | values:{parameter[:2]}")
    print(f" layer name:{name} \n size:{parameter.size()} \n values:{parameter[:2]} \n")
    # print(f" layer name:{name} \n size:{parameter.size()} \n values:{parameter[:2]} \n shape:{parameter[:2].shape}\n")

 layer name:linear_relu.0.weight 
 size:torch.Size([512, 784]) 
 values:tensor([[-0.0123,  0.0006,  0.0081,  ...,  0.0237, -0.0279, -0.0138],
        [ 0.0202, -0.0187,  0.0337,  ..., -0.0250,  0.0039,  0.0160]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

 layer name:linear_relu.0.bias 
 size:torch.Size([512]) 
 values:tensor([-0.0083,  0.0321], device='cuda:0', grad_fn=<SliceBackward0>) 

 layer name:linear_relu.2.weight 
 size:torch.Size([512, 512]) 
 values:tensor([[ 0.0100, -0.0273,  0.0083,  ..., -0.0287, -0.0273, -0.0099],
        [-0.0250, -0.0231, -0.0131,  ...,  0.0011,  0.0376, -0.0348]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

 layer name:linear_relu.2.bias 
 size:torch.Size([512]) 
 values:tensor([-0.0413,  0.0062], device='cuda:0', grad_fn=<SliceBackward0>) 

 layer name:linear_relu.4.weight 
 size:torch.Size([10, 512]) 
 values:tensor([[ 0.0265,  0.0197,  0.0030,  ...,  0.0387,  0.0219,  0.0028],
        [-0.0201, -0.0216, -0.0297,  ...,  0.0242, -0.0