In [1]:
import torch
import torch.nn as nn

In [93]:
input = torch.tensor([[[[1,1,1],[1,1,1],[1,1,1]],[[1,3,2],[2,3,1],[3,1,3]]],
                      [[[2,3,4],[5,6,7],[1,1,1]],[[2,1,3],[2,2,2],[4,1,2]]]],dtype=torch.float32)
# input.size()
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 3., 2.],
          [2., 3., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [5., 6., 7.],
          [1., 1., 1.]],

         [[2., 1., 3.],
          [2., 2., 2.],
          [4., 1., 2.]]]])


In [107]:
bn = nn.BatchNorm2d(2)

In [109]:
output = bn(input)
print(output)

tensor([[[[-0.6070, -0.6070, -0.6070],
          [-0.6070, -0.6070, -0.6070],
          [-0.6070, -0.6070, -0.6070]],

         [[-1.2700,  1.0160, -0.1270],
          [-0.1270,  1.0160, -1.2700],
          [ 1.0160, -1.2700,  1.0160]]],


        [[[-0.0867,  0.4336,  0.9538],
          [ 1.4741,  1.9944,  2.5146],
          [-0.6070, -0.6070, -0.6070]],

         [[-0.1270, -1.2700,  1.0160],
          [-0.1270, -0.1270, -0.1270],
          [ 2.1590, -1.2700, -0.1270]]]], grad_fn=<NativeBatchNormBackward0>)


In [94]:
torch.sum(input,dim=0)    

tensor([[[3., 4., 5.],
         [6., 7., 8.],
         [2., 2., 2.]],

        [[3., 4., 5.],
         [4., 5., 3.],
         [7., 2., 5.]]])

In [96]:
# 不同批次同一通道上的和
torch.sum(torch.sum(input,dim=0)[0])

tensor(39.)

In [110]:
# 均值
m = torch.sum(torch.sum(input,dim=0)[0])/18
print(m)

tensor(2.1667)


In [111]:
# 标准差
std = torch.sqrt((torch.sum(
    torch.pow(input[0][0]-m,2))+torch.sum(torch.pow(input[1][0]-m,2)))/18)
print(std)

tensor(1.9221)


In [112]:
# 计算某个位置BN后的值，可以和前面nn.BatchNorm2d比较，同一位置的结果是一样的！！！
(input[0][1][0][1]-m)/std

tensor(0.4336)