#### pytorch对维度操作的方法

In [1]:
import torch
import torch.nn as nn

In [25]:
# tensor view
input = torch.tensor([[[[1,1,1],[1,1,1],[1,1,1]],[[1,3,2],[2,3,1],[3,1,3]]],
                      [[[2,3,4],[5,6,7],[1,1,1]],[[2,1,3],[2,2,2],[4,1,2]]]],dtype=torch.float32)
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 3., 2.],
          [2., 3., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [5., 6., 7.],
          [1., 1., 1.]],

         [[2., 1., 3.],
          [2., 2., 2.],
          [4., 1., 2.]]]])


In [26]:
print(input.size())
print(input.shape)

torch.Size([2, 2, 3, 3])
torch.Size([2, 2, 3, 3])


In [27]:
in_view = input.view(-1,18)
print(in_view)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 2., 3., 1., 3., 1., 3.],
        [2., 3., 4., 5., 6., 7., 1., 1., 1., 2., 1., 3., 2., 2., 2., 4., 1., 2.]])


## 如果原始张量在所谓的contiguous的前提下，
#### view和reshape方法都是会共享原始张量内存的，所以即使是赋值给新的变量后，对新变量的数据修改，仍然会影响原始张量
## 但是如果不是contiguous,用view和reshape方法就不会再共享原始张量的内存了,
#### 在view之前需要进行contiguous()处理，才能再使用view；
#### 而对于reshape来说，虽然不是contiguous，但是仍然可以直接reshape
#### 比如torch.transpose即转置后就不再是contiguous

In [28]:
in_view[1][17] = 5
print(in_view)
print(input)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 2., 3., 1., 3., 1., 3.],
        [2., 3., 4., 5., 6., 7., 1., 1., 1., 2., 1., 3., 2., 2., 2., 4., 1., 5.]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 3., 2.],
          [2., 3., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [5., 6., 7.],
          [1., 1., 1.]],

         [[2., 1., 3.],
          [2., 2., 2.],
          [4., 1., 5.]]]])


In [29]:
in_reshape = torch.reshape(input,(-1,18))
print(in_reshape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 2., 3., 1., 3., 1., 3.],
        [2., 3., 4., 5., 6., 7., 1., 1., 1., 2., 1., 3., 2., 2., 2., 4., 1., 5.]])


In [30]:
in_reshape[1][17] = 2
print(in_reshape)
print(input)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 2., 3., 1., 3., 1., 3.],
        [2., 3., 4., 5., 6., 7., 1., 1., 1., 2., 1., 3., 2., 2., 2., 4., 1., 2.]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 3., 2.],
          [2., 3., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [5., 6., 7.],
          [1., 1., 1.]],

         [[2., 1., 3.],
          [2., 2., 2.],
          [4., 1., 2.]]]])


In [32]:
in_transpose = torch.transpose(input,1,2)
print(in_transpose)
print(in_transpose.shape)

tensor([[[[1., 1., 1.],
          [1., 3., 2.]],

         [[1., 1., 1.],
          [2., 3., 1.]],

         [[1., 1., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [2., 1., 3.]],

         [[5., 6., 7.],
          [2., 2., 2.]],

         [[1., 1., 1.],
          [4., 1., 2.]]]])
torch.Size([2, 3, 2, 3])


In [36]:
# 不是contiguous，无法使用view方法
in_trans_view = in_transpose.view(-1,18)
print(in_trans_view)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [38]:
in_trans_view = in_transpose.contiguous().view(-1,18)
print(in_trans_view)

tensor([[1., 1., 1., 1., 3., 2., 1., 1., 1., 2., 3., 1., 1., 1., 1., 3., 1., 3.],
        [2., 3., 4., 2., 1., 3., 5., 6., 7., 2., 2., 2., 1., 1., 1., 4., 1., 2.]])


In [39]:
# view后修改数据，不会影响原始张量
in_trans_view[1][17] = 5
print(in_trans_view)
print(in_transpose)

tensor([[1., 1., 1., 1., 3., 2., 1., 1., 1., 2., 3., 1., 1., 1., 1., 3., 1., 3.],
        [2., 3., 4., 2., 1., 3., 5., 6., 7., 2., 2., 2., 1., 1., 1., 4., 1., 5.]])
tensor([[[[1., 1., 1.],
          [1., 3., 2.]],

         [[1., 1., 1.],
          [2., 3., 1.]],

         [[1., 1., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [2., 1., 3.]],

         [[5., 6., 7.],
          [2., 2., 2.]],

         [[1., 1., 1.],
          [4., 1., 2.]]]])


In [40]:
# reshape可以直接使用
in_trans_reshape = in_transpose.reshape(-1,18)
print(in_trans_reshape)

tensor([[1., 1., 1., 1., 3., 2., 1., 1., 1., 2., 3., 1., 1., 1., 1., 3., 1., 3.],
        [2., 3., 4., 2., 1., 3., 5., 6., 7., 2., 2., 2., 1., 1., 1., 4., 1., 2.]])


In [42]:
# reshape后修改数据，不会影响原始张量
in_trans_reshape[1][17] = 6
print(in_trans_reshape)
print(in_transpose)

tensor([[1., 1., 1., 1., 3., 2., 1., 1., 1., 2., 3., 1., 1., 1., 1., 3., 1., 3.],
        [2., 3., 4., 2., 1., 3., 5., 6., 7., 2., 2., 2., 1., 1., 1., 4., 1., 6.]])
tensor([[[[1., 1., 1.],
          [1., 3., 2.]],

         [[1., 1., 1.],
          [2., 3., 1.]],

         [[1., 1., 1.],
          [3., 1., 3.]]],


        [[[2., 3., 4.],
          [2., 1., 3.]],

         [[5., 6., 7.],
          [2., 2., 2.]],

         [[1., 1., 1.],
          [4., 1., 2.]]]])
