In [1]:
import torch

In [14]:
a = torch.arange(2,5)
b = torch.arange(4,6)

In [15]:
a

tensor([2, 3, 4])

In [16]:
b

tensor([4, 5])

In [18]:
# indexing='ij'， 第一个张量表示x坐标，第二个张量表示y坐标，两个张量对应位置的元素组成坐标，结果张量是按坐标系中列方向得出的
# 输入张量为M×N，结果张量中每个张量均是M×N
torch.meshgrid(a, b,indexing='ij')

(tensor([[2, 2],
         [3, 3],
         [4, 4]]),
 tensor([[4, 5],
         [4, 5],
         [4, 5]]))

In [20]:
# indexing = 'xy' ，第一个张量表示x坐标，第二个张量表示y坐标，两个张量对应位置的元素组成坐标，结果张量是按坐标系中行方向得出的
# 输入张量为M×N，结果张量中每个张量均是N×M
torch.meshgrid(a, b,indexing='xy')

(tensor([[2, 3, 4],
         [2, 3, 4]]),
 tensor([[4, 4, 4],
         [5, 5, 5]]))

In [23]:
torch.stack(torch.meshgrid(a, b)).flatten(1)

tensor([[2, 2, 3, 3, 4, 4],
        [4, 5, 4, 5, 4, 5]])